/**
 * Versioned schema migrations — the only way the schema changes.
 *
 * A production database is never edited by hand: a schema change is a new
 * entry at the end of `MIGRATIONS`, merged like any other code, and applied by
 * `store.migrate()` on the next deploy (Railway runs `cli.js migrate` as the
 * pre-deploy step; every CLI command and the API boot run it too). Applied ids
 * are recorded in `schema_migrations`, so each migration runs exactly once per
 * database, in order, inside its own transaction.
 *
 * Rules:
 * - **Append only.** Never edit or reorder a migration that has shipped; a
 *   database that already applied it will never see the change. Fix forward.
 * - **Portable SQL.** Plain SQL valid in SQLite and Postgres. The genuine
 *   dialect differences — identity columns, 8-byte floats, byte-order text —
 *   are the `ID`, `FLOAT` and `TEXT` tokens from `types()`; use them for every
 *   new column. Anything else that differs goes through a `ctx` helper (see
 *   `addColumnIfMissing`) rather than a dialect branch in a migration body.
 * - `INSERT … ON CONFLICT DO UPDATE` only, TEXT for dates, no extensions.
 */

export type Dialect = 'sqlite' | 'postgres';

export interface MigrationContext {
  readonly dialect: Dialect;
  exec(sql: string): Promise<void>;
  columnExists(table: string, column: string): Promise<boolean>;
}

export interface Migration {
  id: number;
  name: string;
  up(ctx: MigrationContext): Promise<void>;
}

/** Dialect-specific spellings of the column types that differ. */
export function types(dialect: Dialect): { ID: string; FLOAT: string; TEXT: string } {
  return dialect === 'postgres'
    ? {
      // BY DEFAULT rather than ALWAYS so `copy-store` can carry ids across verbatim.
      ID: 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
      // Postgres REAL is a 4-byte float, which would silently lose precision.
      FLOAT: 'DOUBLE PRECISION',
      // Byte order, as SQLite sorts. A glibc/ICU locale collation ignores
      // punctuation, so `us_a` would sort before `us.a_b` — every ORDER BY on
      // an id would then depend on how the host happened to initdb.
      TEXT: 'TEXT COLLATE "C"',
    }
    : { ID: 'INTEGER PRIMARY KEY AUTOINCREMENT', FLOAT: 'REAL', TEXT: 'TEXT' };
}

/**
 * Add a column unless it is already there.
 *
 * Exists for databases created before the migration table did: their tables
 * may or may not already have a column depending on which checkout made them.
 */
export async function addColumnIfMissing(
  ctx: MigrationContext, table: string, column: string, definition: string,
): Promise<void> {
  if (await ctx.columnExists(table, column)) return;
  await ctx.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
}

export const MIGRATIONS: Migration[] = [
  {
    id: 1,
    name: 'baseline',
    // Every statement is IF NOT EXISTS, so a database created before
    // versioning (the local world.db) adopts this as already applied without
    // losing anything.
    async up(ctx) {
      const { ID, FLOAT, TEXT } = types(ctx.dialect);
      const statements = [
        `CREATE TABLE IF NOT EXISTS series (
          id                    ${TEXT} PRIMARY KEY,
          name                  ${TEXT} NOT NULL,
          unit                  ${TEXT} NOT NULL,
          cadence               ${TEXT} NOT NULL,
          source_id             ${TEXT} NOT NULL,
          pillar                ${TEXT},
          source_url            ${TEXT},
          notes                 ${TEXT},
          staleness_budget_days INTEGER NOT NULL DEFAULT 7
        )`,
        `CREATE INDEX IF NOT EXISTS idx_series_source ON series (source_id)`,
        `CREATE INDEX IF NOT EXISTS idx_series_pillar ON series (pillar)`,

        `CREATE TABLE IF NOT EXISTS observations (
          series_id ${TEXT} NOT NULL,
          obs_date  ${TEXT} NOT NULL,
          value     ${FLOAT} NOT NULL,
          PRIMARY KEY (series_id, obs_date)
        )`,
        `CREATE INDEX IF NOT EXISTS idx_obs_date ON observations (obs_date)`,

        `CREATE TABLE IF NOT EXISTS source_runs (
          id             ${ID},
          source_id      ${TEXT} NOT NULL,
          started_at     ${TEXT} NOT NULL,
          finished_at    ${TEXT} NOT NULL,
          status         ${TEXT} NOT NULL,
          rows_written   INTEGER NOT NULL DEFAULT 0,
          events_written INTEGER NOT NULL DEFAULT 0,
          error          ${TEXT}
        )`,
        `CREATE INDEX IF NOT EXISTS idx_runs_source ON source_runs (source_id, started_at DESC)`,

        // One row per pipeline stage execution, written even when the stage
        // throws. Without it a scheduler that stopped firing is invisible.
        `CREATE TABLE IF NOT EXISTS pipeline_runs (
          id           ${ID},
          stage        ${TEXT} NOT NULL,
          started_at   ${TEXT} NOT NULL,
          finished_at  ${TEXT} NOT NULL,
          status       ${TEXT} NOT NULL,
          ok_count     INTEGER NOT NULL DEFAULT 0,
          fail_count   INTEGER NOT NULL DEFAULT 0,
          rows_written INTEGER NOT NULL DEFAULT 0,
          error        ${TEXT},
          detail       ${TEXT}
        )`,
        `CREATE INDEX IF NOT EXISTS idx_pipeline_stage ON pipeline_runs (stage, started_at DESC)`,

        `CREATE TABLE IF NOT EXISTS series_health (
          series_id       ${TEXT} PRIMARY KEY,
          last_obs_date   ${TEXT},
          last_success_at ${TEXT}
        )`,

        `CREATE TABLE IF NOT EXISTS scores (
          score_date ${TEXT} NOT NULL,
          key        ${TEXT} NOT NULL,
          kind       ${TEXT} NOT NULL,
          value      ${FLOAT} NOT NULL,
          inputs     ${TEXT} NOT NULL,
          PRIMARY KEY (score_date, key)
        )`,
        `CREATE INDEX IF NOT EXISTS idx_scores_kind ON scores (kind, score_date DESC)`,

        `CREATE TABLE IF NOT EXISTS events (
          id        ${TEXT} PRIMARY KEY,
          ts        ${TEXT} NOT NULL,
          source_id ${TEXT} NOT NULL,
          category  ${TEXT} NOT NULL,
          headline  ${TEXT} NOT NULL,
          url       ${TEXT} NOT NULL,
          severity  ${FLOAT} NOT NULL DEFAULT 0,
          entities  ${TEXT}
        )`,
        `CREATE INDEX IF NOT EXISTS idx_events_ts ON events (ts DESC)`,
        `CREATE INDEX IF NOT EXISTS idx_events_category ON events (category, ts DESC)`,

        // Verbatim upstream responses, for replay after a parsing bug.
        `CREATE TABLE IF NOT EXISTS raw_cache (
          cache_key  ${TEXT} PRIMARY KEY,
          source_id  ${TEXT} NOT NULL,
          url        ${TEXT} NOT NULL,
          fetched_at ${TEXT} NOT NULL,
          body       ${TEXT} NOT NULL
        )`,
        `CREATE INDEX IF NOT EXISTS idx_raw_cache_source ON raw_cache (source_id, fetched_at DESC)`,
      ];
      for (const s of statements) await ctx.exec(s);
    },
  },
  {
    id: 2,
    name: 'series_retired_at',
    // A discontinued upstream series: never fetched, never stale, history kept.
    async up(ctx) {
      await addColumnIfMissing(ctx, 'series', 'retired_at', types(ctx.dialect).TEXT);
    },
  },
  {
    id: 3,
    name: 'drop_raw_cache',
    // Upstream bodies moved to a ResponseCache (object store or directory,
    // `WD_CACHE_URL`). They were ~60% of the database, rarely read, and refill
    // themselves on the next fetch, so nothing is carried across.
    async up(ctx) {
      await ctx.exec('DROP INDEX IF EXISTS idx_raw_cache_source');
      await ctx.exec('DROP TABLE IF EXISTS raw_cache');
    },
  },
];

/** The table `migrate()` records applied ids in. Identical in both dialects. */
export const MIGRATIONS_TABLE_DDL = `CREATE TABLE IF NOT EXISTS schema_migrations (
  id         INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  applied_at TEXT NOT NULL
)`;
